import React from "react";
import { useFormContext } from "react-hook-form";
import { PDFDownloadLink } from "@react-pdf/renderer";
import CVDocument from "./pdf/CVDocument"; // 👈 Importing the PDF Template
import {
  Mail,
  Phone,
  Briefcase,
  GraduationCap,
  Wrench,
  Linkedin,
  Github,
  User,
  FileText,
  Download,
} from "lucide-react";

// Helper component for consistent section headers in the Web View
const SectionHeader = ({ icon: Icon, title }) => (
  <h3 className="flex items-center gap-2 pb-1 mt-6 mb-4 text-lg font-bold text-gray-800 uppercase border-b-2 border-gray-300">
    <Icon size={18} className="text-gray-700" /> {title}
  </h3>
);

const CVPreview = () => {
  const { watch } = useFormContext();
  const data = watch();

  // Check if we need to render the bottom section
  const hasBioData =
    data.personalInfo.address ||
    data.personalInfo.dob ||
    data.personalInfo.gender ||
    data.personalInfo.nationality ||
    data.personalInfo.maritalStatus ||
    data.personalInfo.idNumber;

  return (
    <div className="sticky top-0 h-screen p-4 overflow-y-auto bg-gray-100 border-l border-gray-200">
      {/* --- CONTROLS SECTION --- */}
      <div className="flex justify-between items-center mb-4 px-2 max-w-[210mm] mx-auto">
        <h2 className="text-lg font-bold text-gray-800">Live Preview</h2>

        {/* 👇 THE NEW DOWNLOAD BUTTON (Uses @react-pdf/renderer) */}
        <PDFDownloadLink
          document={<CVDocument data={data} />}
          fileName={`${data.personalInfo.fullName || "resume"}.pdf`}
          className="flex items-center gap-2 px-4 py-2 text-sm font-bold text-white no-underline transition bg-blue-600 rounded shadow-sm hover:bg-blue-700"
        >
          {({ loading }) => (
            <>
              <Download size={16} />
              {loading ? "Generating..." : "Download PDF"}
            </>
          )}
        </PDFDownloadLink>
      </div>

      {/* --- WEB VISUAL PREVIEW --- */}
      {/* This section is now just for "Looks", the actual PDF is generated by CVDocument */}
      <div
        className="bg-white shadow-2xl mx-auto p-[15mm] w-[210mm] min-h-[297mm]"
        id="cv-print-area"
      >
        {/* --- 1. HEADER (Contact Only) --- */}
        <header className="flex items-start gap-6 pb-6 mb-2 border-b-2 border-gray-800">
          {data.personalInfo.photo && (
            <img
              src={data.personalInfo.photo}
              alt="Profile"
              className="w-[35mm] h-[35mm] rounded-full object-cover border-2 border-gray-200"
            />
          )}

          <div className="flex-1 pt-2">
            <h1 className="text-4xl font-extrabold leading-none tracking-tight text-gray-900 uppercase">
              {data.personalInfo.fullName || "Your Name"}
            </h1>
            <p className="mt-2 text-xl font-medium text-gray-600">
              {data.personalInfo.role || "Job Title"}
            </p>

            {/* Contact Grid - Fixed Links & No Truncation */}
            <div className="flex flex-wrap mt-4 text-sm text-gray-700 gap-x-6 gap-y-2">
              {data.personalInfo.email && (
                <div className="flex items-center gap-1">
                  <Mail size={14} className="shrink-0" />{" "}
                  {data.personalInfo.email}
                </div>
              )}
              {data.personalInfo.phone && (
                <div className="flex items-center gap-1">
                  <Phone size={14} className="shrink-0" />{" "}
                  {data.personalInfo.phone}
                </div>
              )}

              {/* LinkedIn - Full Clickable Link */}
              {data.personalInfo.linkedin && (
                <a
                  href={
                    data.personalInfo.linkedin.startsWith("http")
                      ? data.personalInfo.linkedin
                      : `https://${data.personalInfo.linkedin}`
                  }
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-1 text-blue-700 hover:underline"
                >
                  <Linkedin size={14} className="shrink-0" />
                  <span className="break-all">
                    {data.personalInfo.linkedin.replace(
                      /^https?:\/\/(www\.)?/,
                      ""
                    )}
                  </span>
                </a>
              )}

              {/* GitHub - Full Clickable Link */}
              {data.personalInfo.github && (
                <a
                  href={
                    data.personalInfo.github.startsWith("http")
                      ? data.personalInfo.github
                      : `https://${data.personalInfo.github}`
                  }
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center gap-1 text-gray-800 hover:underline"
                >
                  <Github size={14} className="shrink-0" />
                  <span className="break-all">
                    {data.personalInfo.github.replace(
                      /^https?:\/\/(www\.)?/,
                      ""
                    )}
                  </span>
                </a>
              )}
            </div>
          </div>
        </header>

        {/* --- 2. PROFESSIONAL SUMMARY (New Separate Section) --- */}
        {data.personalInfo.summary && (
          <section>
            <SectionHeader icon={FileText} title="Professional Summary" />
            <p className="text-sm leading-relaxed text-justify text-gray-700 whitespace-pre-line">
              {data.personalInfo.summary}
            </p>
          </section>
        )}

        {/* --- 3. EXPERIENCE --- */}
        {data.experience?.length > 0 && (
          <section>
            <SectionHeader icon={Briefcase} title="Experience" />
            <div className="space-y-5">
              {data.experience.map((job, index) => (
                <div key={index}>
                  <div className="flex items-baseline justify-between">
                    <h4 className="font-bold text-gray-900 text-md">
                      {job.role}
                    </h4>
                    <span className="text-sm font-medium text-gray-500 whitespace-nowrap">
                      {job.startDate} — {job.endDate}
                    </span>
                  </div>
                  <p className="mb-1 text-sm font-medium text-blue-600">
                    {job.company}
                  </p>
                  <p className="text-sm leading-relaxed text-justify text-gray-700 whitespace-pre-line">
                    {job.description}
                  </p>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* --- 4. EDUCATION --- */}
        {data.education?.length > 0 && (
          <section>
            <SectionHeader icon={GraduationCap} title="Education" />
            <div className="space-y-4">
              {data.education.map((edu, index) => (
                <div key={index} className="flex items-start justify-between">
                  <div>
                    <h4 className="font-bold text-gray-900">{edu.school}</h4>
                    <p className="text-sm text-gray-600">{edu.degree}</p>
                  </div>
                  <span className="text-sm font-medium text-gray-500 whitespace-nowrap">
                    {edu.date}
                  </span>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* --- 5. SKILLS --- */}
        {data.skills?.length > 0 && (
          <section>
            <SectionHeader icon={Wrench} title="Skills" />
            <div className="flex flex-wrap gap-2">
              {data.skills.map((skill, index) => (
                <span
                  key={index}
                  className="px-3 py-1 text-sm font-medium text-gray-800 bg-gray-100 border border-gray-300 rounded"
                >
                  {skill.name}
                </span>
              ))}
            </div>
          </section>
        )}

        {/* --- 6. PERSONAL INFORMATION (Clean Grid Layout) --- */}
        {hasBioData && (
          <section>
            <SectionHeader icon={User} title="Personal Information" />

            <div className="grid grid-cols-1 text-sm md:grid-cols-2 gap-x-12 gap-y-3">
              {data.personalInfo.address && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    Address
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.address}
                  </span>
                </div>
              )}
              {data.personalInfo.dob && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    Date of Birth
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.dob}
                  </span>
                </div>
              )}
              {data.personalInfo.gender && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    Gender
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.gender}
                  </span>
                </div>
              )}
              {data.personalInfo.nationality && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    Nationality
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.nationality}
                  </span>
                </div>
              )}
              {data.personalInfo.maritalStatus && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    Marital Status
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.maritalStatus}
                  </span>
                </div>
              )}
              {data.personalInfo.idNumber && (
                <div className="grid grid-cols-[140px_1fr] border-b border-gray-100 pb-1">
                  <span className="text-xs font-semibold tracking-wide text-gray-500 uppercase">
                    NIC / Passport
                  </span>
                  <span className="font-medium text-gray-900">
                    {data.personalInfo.idNumber}
                  </span>
                </div>
              )}
            </div>
          </section>
        )}
      </div>
    </div>
  );
};

export default CVPreview;
